spring:
  application:
    name: spring-boot-batch-app
  datasource:
    username: postgres
    password: Onkarkadam27@
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/department_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
server:
  port: 8081